version: "3.7"
services:
  rabbitmq:
    container_name: celery-rabbitmq
    image: "rabbitmq:3-management"
    ports:
    - "5672:5672"
    - "15672:15672"      
  flower:
    container_name: celery-flower
    build: ./flower
    ports:
    - "5555:5555"
    depends_on:
    - rabbitmq
  postgres:
    container_name: celery-postgres
    build: ./postgres      
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  worker:
    container_name: celery-worker
    build: ./worker
    depends_on:
    - rabbitmq
  beat:
    container_name: celery-beat
    build: ./beat    
    depends_on:
    - rabbitmq
